language: python
python:
  - "2.7"
  - "2.6"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 argparse; fi
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - python setup.py install
script:
    - nosetests tests --with-coverage --cover-erase --cover-package=bwa
after_success:
    - coveralls
